FROM ghcr.io/seisscoped/container-base:centos7

LABEL maintainer="Yiyu Ni"

RUN  cd /home/scoped \
    && git clone https://github.com/noisepy/noisepy.git \
    && git pull \
    && cd noisepy \
    && pip install ".[dev,aws]"