FROM ghcr.io/seisscoped/container-base:centos7_jupyterlab

LABEL maintainer="Yiyu Ni"

RUN  cd /home/scoped \
    && git clone --depth=1 https://github.com/noisepy/noisepy.git \
    && git pull \
    && cd noisepy \
    && pip install ".[dev,aws]"
